services:
  app:
    image: app:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-s3cr3t}
      - DB_NAME=${DB_NAME:-app}
    deploy:
      replicas: 3 # Number of instances to run
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx:1.26.2-alpine
    ports:
      - '8080:80' # Map host port 8080 to container port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mount the custom Nginx config
    depends_on:
      - app

  db:
    image: postgres:15
    ports:
      - '5432:5432' # Map host port 8080 to container port 80
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-s3cr3t}
    volumes:
      - ./db/data:/var/lib/postgresql/data # Persist data
      - ./db/scripts/init-db.sql:/docker-entrypoint-initdb.d/init.sql # Run init script
